Revert "Remove vala from the runtime"
This reverts commit 6a9ed593d318476bb8950ae670ecfabda3c82b21.

We need to try again tomorrow. Epiphany is busted on startup due to
missing libgee in the runtime. It's not possible to bundle libgee
because it cannot be built because the Vala extension does not ship the
vala.m4 macros required to build vala projects using autotools, and
libgee uses autotools. This is fixed by:

https://gitlab.gnome.org/GNOME/vala/-/merge_requests/326

And a new extension has been successfully built. However, we cannot
deploy the new extension to gnome-runtime-images for aarch64 due to a
disk space issue:

https://gitlab.gnome.org/GNOME/gnome-runtime-images/-/jobs/2916396

Error: committing container "gnome-runtime-images-working-container" to "quay.io/gnome_infrastructure/gnome-runtime-images:aarch64-gnome-master": copying layers and metadata for container "eb8bc39da1fab8d04b9dd5ff7d447cd4f811e4c695ab8cd901c695e37723d097": writing blob: storing blob to file "/var/tmp/storage2546246784/1": write /var/tmp/storage2546246784/1: no space left on device

In the meantime, all users of Epiphany Tech Preview cannot start their
browsers. We'll need to try this again after the infrastructure problem
has been resolved.

Part-of: <https://gitlab.gnome.org/GNOME/gnome-build-meta/-/merge_requests/2225>