vm: Upgrade toolbox
Vendored upstream builds make things easier

Zsh completions target would fail with
> Error: failed to get the cgroups version: no such file or directory

The upstream fixes don't appear to work in our case but anyway we don't
have zsh so we don't need this target.

Part-of: <https://gitlab.gnome.org/GNOME/gnome-build-meta/-/merge_requests/2032>