sdk/libsecret.bst: add valgrind as a build dependency
Looks like this is only used by the testsuite as of now, so
its only a build dep, not runtime one.

```
        FAILED: egg/34707c3@@egg@sta/egg-testing.c.o
        cc -Iegg/34707c3@@egg@sta -Iegg -I../egg -I. -I../ -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/libffi-3.2.1/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/x86_64-linux-gnu -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -march=x86-64 -mtune=generic -O2 -g -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -pthread -MD -MQ 'egg/34707c3@@egg@sta/egg-testing.c.o' -MF 'egg/34707c3@@egg@sta/egg-testing.c.o.d' -o 'egg/34707c3@@egg@sta/egg-testing.c.o' -c ../egg/egg-testing.c
        ../egg/egg-testing.c:30:10: fatal error: valgrind/valgrind.h: No such file or directory
           30 | #include <valgrind/valgrind.h>
              |          ^~~~~~~~~~~~~~~~~~~~~
        compilation terminated.
```